### ISSUE TITLE
Port strategy functions

### ISSUE THREAD

**Issue by bitcoinbrisbane** [naladao/yearn-vaults#7]
- [x] addStrategy
- [x] updateStrategyDebtRatio
- [x] updateStrategyMinDebtPerHarvest
- [x] updateStrategyPerformanceFee
- [x] _revokeStrategy
- [x] revokeStrategy

**Comment by LichuAcu** [comment]
- [ ] updateStrategyMaxDebtPerHarvest

**Comment by LichuAcu** [comment]
- [ ] setHealthCheck

**Comment by bitcoinbrisbane** [comment]
#14 closes this
